import type { User, Property } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "john.owner@example.com",
    name: "John Smith",
    role: "owner",
    avatar: "/professional-man.png",
    phone: "(555) 123-4567",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "sarah.tenant@example.com",
    name: "Sarah Johnson",
    role: "tenant",
    avatar: "/professional-woman-diverse.png",
    phone: "(555) 987-6543",
    createdAt: new Date("2024-02-20"),
  },
]

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    description:
      "Beautiful 2-bedroom apartment in the heart of downtown with stunning city views, modern appliances, and walking distance to restaurants and shopping.",
    price: 2500,
    location: {
      address: "123 Main Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    images: ["/modern-apartment-living-room.png", "/modern-kitchen.png", "/city-view-bedroom.png"],
    amenities: ["Air Conditioning", "Dishwasher", "Gym", "Parking", "Pet Friendly", "Laundry"],
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    availableFrom: new Date("2024-04-01"),
    ownerId: "1",
    owner: mockUsers[0],
    featured: true,
    status: "available",
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "2",
    title: "Cozy Studio Near University",
    description:
      "Perfect studio apartment for students or young professionals. Recently renovated with modern fixtures and great natural light.",
    price: 1800,
    location: {
      address: "456 College Ave",
      city: "Berkeley",
      state: "CA",
      zipCode: "94704",
    },
    images: ["/cozy-studio-apartment.png", "/small-modern-kitchen.png", "/studio-bathroom.png"],
    amenities: ["Air Conditioning", "Laundry", "Internet Included"],
    propertyType: "studio",
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 500,
    availableFrom: new Date("2024-03-15"),
    ownerId: "1",
    owner: mockUsers[0],
    featured: false,
    status: "available",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "3",
    title: "Spacious Family House",
    description:
      "Beautiful 4-bedroom house with large backyard, perfect for families. Located in a quiet neighborhood with excellent schools nearby.",
    price: 4200,
    location: {
      address: "789 Oak Street",
      city: "Palo Alto",
      state: "CA",
      zipCode: "94301",
    },
    images: ["/modern-family-house.png", "/spacious-living-room.png", "/backyard-garden.png"],
    amenities: ["Air Conditioning", "Dishwasher", "Parking", "Pet Friendly", "Laundry", "Garden"],
    propertyType: "house",
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2800,
    availableFrom: new Date("2024-05-01"),
    ownerId: "1",
    owner: mockUsers[0],
    featured: true,
    status: "available",
    createdAt: new Date("2024-03-10"),
  },
]
